### ISSUE TITLE
Geschweifte Klammern im Codebeispiel

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Formal-Languages#24]
In `Formal-Languages/Lecture-Notes/antlr.tex` in Zeile `117` erwähnen Sie eine Aktion in geschweiften Klammern. Im Codebeispiel sind jedoch keine geschweiften Klammern vorhanden.
Ist dies ein Fehler im Codebeispiel oder in der Beschreibung; oder habe ich hier etwas übersehen?

**Comment by karlstroetmann** [comment]
Da hatte ich das Beispiel geändert, aber vergessen, auch die Diskussion des Beispiels entsprechend zu ändern.  Jetzt habe ich auch die Beschreibung angepasst.  Vielen Dank für den Hinweis!
