### ISSUE TITLE
Makefile not working

### ISSUE THREAD

**Issue by Danghor** [karlstroetmann/Formal-Languages#37]
I tried to generate a pdf from source using the Makefile. However, I always get the error

```batch
! pdfTeX error (\pdfmapline): not allowed in DVI mode (\pdfoutput <= 0)
```

when trying to create the `.dvi` file with latex. Is the Makefile working for you or are you generating the PDF in a different way? Also, may I ask which TeX distribution you are using?

**Comment by karlstroetmann** [comment]
I generate the pdf using TeXshop.  The Makefile is old and not needed anymore.  I will remove it.
